env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[fcb376130f47e19f208d2987095d2319a82b120a7f72b7f1ba95aa291ea041fdd472eda5751261991271c02bf1509b6e]"
  TG_TOKEN: "ENCRYPTED[79fd6bcceff7ccd0425e9d6d976e4fd0ca738ca7065505af886250b53a89efe2ae3ef54d250b8169c9cbb94c8244340b]"
  TG_CHAT_ID: "ENCRYPTED[ad7bafd47f38be7bb193de809c7be65f75eec911789aa477861d4744f315f403645334057c096bec2db780d9c13f505f]"
  CREDENTIALS: "ENCRYPTED[37574ce2f42f08e4c014c10eb629f6ca414db4fca54ba67780e066e20b7cef872644bba5533f9d1df3d188313fff67dd]"
  USER: "ENCRYPTED[8db3fca0e274855fea820b91a5892de83ad6422e7b9dc0b34de6cf56eb0520957bdc109480d38a154b322a77a3894494]"
  EMAIL: "ENCRYPTED[54da6d59d960014db4571488fc27eb23079911841bef658fdd7ffa8b4b301c25e39e6f9d56734d4ee2bf1fa92d5993cc]"
  KBUILD_BUILD_USER: "ENCRYPTED[2d6c3f3ba7dd0f40e729ae03a0e9985572b99b9355ba7737e9115b6c6e3813ca7c31d86fe6d359e090084866aaf8f21a]"
  KBUILD_BUILD_HOST: "ENCRYPTED[f10144fdad1158c603c106ce7e258431736712b9716eb0881cb77211d7f6d68dde328878ba13d91c0067fb9c41574aea]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'losgw'
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "$USER"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - export KBUILD_BUILD_USER=$KBUILD_BUILD_USER
     - export KBUILD_BUILD_HOST=$KBUILD_BUILD_USER
     - export BUILD_USERNAME=$KBUILD_BUILD_USER
     - export BUILD_HOSTNAME=$KBUILD_BUILD_USER


  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/mengemas.sh
